//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    public sealed partial class SharedSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SharedSettings defaultInstance = ((SharedSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SharedSettings())));
        
        public static SharedSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SInstallDirPath {
            get {
                return ((string)(this["SInstallDirPath"]));
            }
            set {
                this["SInstallDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3393")]
        public int SHttpPort {
            get {
                return ((int)(this["SHttpPort"]));
            }
            set {
                this["SHttpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3394")]
        public int SHttpsPort {
            get {
                return ((int)(this["SHttpsPort"]));
            }
            set {
                this["SHttpsPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SIISexConfigPath {
            get {
                return ((string)(this["SIISexConfigPath"]));
            }
            set {
                this["SIISexConfigPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SIISexExe {
            get {
                return ((string)(this["SIISexExe"]));
            }
            set {
                this["SIISexExe"] = value;
            }
        }
    }
}
